mysite/disks/urls.py
from django.urls import path

from . import views

app_name = 'disks'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='album_detail'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('disks/', include('disks.urls'))
]

mysite/disks/models.py
from django.db import models


class Artist(models.Model):
    name = models.CharField(max_length=200)

class Album(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    
class Track(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    composer = models.CharField(max_length=200, null=True)
    milliseconds = models.IntegerField(default=0)
    bytes = models.IntegerField(default=0)
    unitPrice = models.FloatField(default=0.0)

mysite/disks/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from .models import Album


class IndexView(generic.ListView):
    template_name = 'disks/index.html'
    context_object_name = 'album_list'

    def get_queryset(self):
        """Return all the albums"""
        return Album.objects.order_by('artist')


class DetailView(generic.DetailView):
    template_name = 'disks/detail.html'
    
    def get_queryset(self):
        """
        get details of the album
        """
        return Album.objects.order_by('title')

mysite/disks/templates/disks/detail.html
<h1>{{ album.title }}</h1>

<table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Composer</th>
        <th>Milliseconds</th>
        <th>Bytes</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
    {% for track in album.track_set.all %} 
      <tr>
        <th> {{track.name}}</th>
        <th> {{track.composer}}</th>
        <th> {{track.milliseconds}}</th>
        <th> {{track.bytes}}</th>
        <th> {{track.unitPrice}}</th>
      </tr>
    {% endfor %}
    </tbody>
</table>

mysite/disks/templates/disks/index.html
{% if album_list %}
    <ul>
    {% for album in album_list %}
    <li><a href="{% url 'disks:album_detail' album.id %}">{{ album.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No albums are available.</p>
{% endif %}